server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://111.231.194.147:3306/fileServer?characterEncoding=UTF-8
    username: fileServer
    password: fileServer
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect